
name: Scala CI

on:
  pull_request:
    types: [opened,reopened,edited] 
    branches: [ "main" ]
   
jobs:
  build_sbt:
    name: Build Project using sbt with native client
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        scala: [2.13.13,3.3.3]
        java: [temurin@17]
    runs-on: ${{matrix.os}}
    env:
      SBT_NATIVE_CLIENT: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
       
      - name : Build Project
        run: sbt compile 
  
